### ISSUE TITLE
Get macOS tests to run on Travis CI again

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/pymongo-feedstock#3]
Unfortunately it seems that Travis CI is doing something that mucks with our ability to startup and/or connect to `mongod`. As a result, we can't run tests that require interacting with `mongod`. Since others have reported being able to run the tests on macOS locally (including myself), it seems like this issue is localized to Travis CI specifically. This problematic behavior is demonstrated in this [TravisCI log]( https://travis-ci.org/conda-forge/pymongo-feedstock/builds/311631125 ). Relevant discussion can be found in PR ( https://github.com/conda-forge/pymongo-feedstock/pull/2 ).

cc @CJ-Wright

**Comment by wolfv** [comment]
looks like this is solved #36
