### ISSUE TITLE
Possibility of building packages for pymongo 3 for newer versions of python

### ISSUE THREAD

**Issue by scarlehoff** [conda-forge/pymongo-feedstock#95]
### Comment:

Would it be possible to build pymongo 3 for newer version of pythons? (e.g., 3.12, 3.13)

Assuming, of course, that they work out of the box. Sadly there are many packages that still depend on pymongo 3, which cascades down and limit other packages to python 3.11 due to that.

**Comment by xylar** [comment]
We could try building 3.13.0 for python 3.12 and 3.13 but there's no indication that it's supported:
https://github.com/mongodb/mongo-python-driver/blob/3.13.0/setup.py#L423

**Comment by xylar** [comment]
It looks like at least the rudimentary testing done by CI is passing with python 3.12 and 3.13.  I'd be in favor of giving it a go in #96.  I'll see if anyone raises concerns.

**Comment by scarlehoff** [comment]
Thanks a lot for this!
